# Generated by Django 3.2.15 on 2022-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
