# Generated by Django 3.2.15 on 2022-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0004_auto_20221012_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
