# Generated by Django 3.2.15 on 2022-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0005_user_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='sname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='spwd',
            field=models.CharField(max_length=50),
        ),
    ]
