# Generated by Django 3.2.15 on 2022-10-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0006_auto_20221012_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='create_time',
            field=models.CharField(max_length=100),
        ),
    ]
