# Generated by Django 3.2.15 on 2022-10-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0007_alter_user_info_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneryAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenery', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('many_people', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'scenery',
            },
        ),
        migrations.CreateModel(
            name='SceneryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenery_name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('scenery_detail', models.CharField(max_length=255)),
                ('scenery_other', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=25)),
                ('rank', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'scenery_detail',
            },
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
