# Generated by Django 3.2.16 on 2022-10-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0008_auto_20221020_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sceneryall',
            options={'verbose_name': '城市景点', 'verbose_name_plural': '城市景点'},
        ),
        migrations.AlterModelOptions(
            name='scenerydetail',
            options={'verbose_name': '景点详情', 'verbose_name_plural': '景点详情'},
        ),
        migrations.AddField(
            model_name='sceneryall',
            name='image_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
