# Generated by Django 3.2.16 on 2022-10-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0009_auto_20221025_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenerySee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenery_name', models.CharField(max_length=45)),
                ('scenery_detail', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=25)),
                ('rank', models.CharField(max_length=80)),
                ('scenery_address', models.CharField(max_length=255)),
                ('scenery_way', models.CharField(max_length=255)),
                ('scenery_open', models.CharField(max_length=255)),
                ('scenery_menpiao', models.CharField(max_length=255)),
                ('scenery_other', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '景点介绍',
                'verbose_name_plural': '景点介绍',
                'db_table': 'scenery_web',
            },
        ),
    ]
