# Generated by Django 3.2.16 on 2022-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0010_scenerysee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45)),
                ('many_people', models.CharField(max_length=45)),
                ('city_image', models.CharField(max_length=45)),
                ('city_detail', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '热门城市',
                'verbose_name_plural': '热门城市',
                'db_table': 'hot_city',
            },
        ),
    ]
