# Generated by Django 3.2.16 on 2022-11-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0011_hotcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotcity',
            name='many_people',
            field=models.IntegerField(max_length=45),
        ),
    ]
