# Generated by Django 3.2.16 on 2022-11-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0012_alter_hotcity_many_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneryAll',
        ),
    ]
