# Generated by Django 3.2.16 on 2022-11-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0013_delete_sceneryall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneryAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenery', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('scenery_detail', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': '城市景点',
                'verbose_name_plural': '城市景点',
                'db_table': 'scenery',
            },
        ),
    ]
