# Generated by Django 3.2.16 on 2022-11-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0014_sceneryall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotcity',
            name='many_people',
            field=models.IntegerField(),
        ),
    ]
