# Generated by Django 3.2.16 on 2022-11-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0015_alter_hotcity_many_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionScenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=45)),
                ('options', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '景点评论管理',
                'verbose_name_plural': '景点评论管理',
                'db_table': 'scenery_option',
            },
        ),
        migrations.CreateModel(
            name='OptionWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=45)),
                ('options', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '路线评论管理',
                'verbose_name_plural': '路线评论管理',
                'db_table': 'way_option',
            },
        ),
    ]
