# Generated by Django 3.2.16 on 2022-11-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0016_optionscenery_optionway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenerys', models.CharField(max_length=85)),
                ('start_time', models.CharField(max_length=85)),
                ('days', models.CharField(max_length=45)),
                ('say_people', models.CharField(max_length=45)),
                ('is_on', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': '路线管理',
                'verbose_name_plural': '路线管理',
                'db_table': 'all_way',
            },
        ),
    ]
