# Generated by Django 3.2.16 on 2022-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0017_ways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ways',
            name='say_people',
            field=models.IntegerField(),
        ),
    ]
