# Generated by Django 3.2.16 on 2022-11-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0018_alter_ways_say_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=85)),
                ('date', models.CharField(max_length=85)),
                ('is_on', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '路线详情',
                'verbose_name_plural': '路线详情',
                'db_table': 'way_info',
            },
        ),
        migrations.CreateModel(
            name='WayScenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=85)),
                ('scenery', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=45)),
                ('is_on', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
