# Generated by Django 3.2.16 on 2022-11-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0019_wayinfo_wayscenery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wayscenery',
            options={'verbose_name': '路线景区', 'verbose_name_plural': '路线景区'},
        ),
        migrations.AlterModelTable(
            name='wayinfo',
            table='ways_info',
        ),
        migrations.AlterModelTable(
            name='wayscenery',
            table='ways_scenery',
        ),
    ]
