# Generated by Django 3.2.16 on 2022-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0020_auto_20221110_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=85)),
                ('date', models.CharField(max_length=85)),
                ('scenery', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=85)),
                ('user', models.CharField(max_length=85)),
                ('say_people', models.CharField(max_length=85)),
                ('is_web', models.CharField(max_length=85)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户自定义路线管理',
                'verbose_name_plural': '用户自定义路线管理',
                'db_table': 'user_way',
            },
        ),
    ]
