# Generated by Django 3.2.16 on 2022-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0023_userscenery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userways',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
