# Generated by Django 3.2.16 on 2022-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0024_userways_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userways',
            name='create_time',
        ),
    ]
