# Generated by Django 3.2.16 on 2022-11-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0025_remove_userways_create_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWays',
        ),
    ]
