# Generated by Django 3.2.16 on 2022-11-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0029_userways'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenery',
            name='user',
            field=models.CharField(default='', max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userways',
            name='user',
            field=models.CharField(default='', max_length=85),
            preserve_default=False,
        ),
    ]
