# Generated by Django 3.2.16 on 2022-12-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0030_auto_20221124_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionway',
            name='is_on',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
