# Generated by Django 3.2.16 on 2022-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0031_optionway_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionway',
            name='option_time',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
