# Generated by Django 3.2.16 on 2022-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0032_optionway_option_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionscenery',
            name='options_time',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionscenery',
            name='scenery',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
