# Generated by Django 3.2.16 on 2022-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0033_auto_20221209_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=85)),
                ('myself', models.CharField(max_length=255)),
                ('good_at', models.CharField(max_length=255)),
                ('go_way', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=85)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '账号安全管理',
                'verbose_name_plural': '账号安全管理',
                'db_table': 'user_safe',
            },
        ),
    ]
