# Generated by Django 3.2.16 on 2022-12-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0035_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneryAdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=85)),
                ('scenery', models.CharField(max_length=85)),
                ('location', models.CharField(max_length=120)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '景区经纬度管理',
                'verbose_name_plural': '景区经纬度管理',
                'db_table': 'scenery_adds',
            },
        ),
    ]
